'''
Main Snakefile.
The aim is to run the cellranger pipeline automatically on all the samples defined in the config file
'''

# Path of the config file
configfile: 'config/config.yaml'

# Rules to execute the workflow
include: 'rules/analysis.smk'

# # Master rule that launches the workflow
# rule all_test:
#     '''
#     Dummy rule to automatically generate up to the vireo demultiplexing assessment.
#     '''
#     input:
#         expand(rules.run_cellranger_test.output.output, sample=config['SAMPLES'])

# # Master rule that launches the workflow
# rule all_test:
#     '''
#     Dummy rule to automatically generate up to the vireo demultiplexing assessment.
#     '''
#     input:
#         expand(rules.run_cellranger.output.folder, sample=config['SAMPLES'])


# Master rule that launches the workflow
rule all_test:
    '''
    Dummy rule to automatically generate up to the vireo demultiplexing assessment.
    '''
    input:
        expand(rules.move_cellranger.output.summary, sample=config['SAMPLES'])


# test rule
rule test:
    '''
    This is a test rule
    '''
    input:
        test = config['test01']
    conda:
        config['env_cellranger']
    output:
        test = 'resources/test_out.txt'
    log:
        'logs/test/test.log'
    benchmark:
        'benchmarks/test/test.txt'
    resources:
        mem_mb = 500,
        cpus = 1
    threads: 1
    params:
        annotations = config['test02']
    shell:
        '''
        echo "run the test" > {log}
        cat {input.test} > {output.test}
        cat {params.annotations} | awk 'NR<=10' >> {output.test}
        echo "test done" >> {log}
        '''
